#ifndef EXTERNTEMPLATEDESCRIPTOR_H
#define EXTERNTEMPLATEDESCRIPTOR_H


#ifdef EXPLICIT_INSTANTS

#include "transporttypes.h"
#include "diffusionvelocitydescriptor.h"
#include "porositytrtdescriptor.h"


#define EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_2D(CLASS_TYPE) \
    template CLASS_TYPE<IPP::TransportFloatingPointType, IPP::PorosityTRTDescriptor::DiffusionDescriptor2D>;

#define EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_3D(CLASS_TYPE) \
    template CLASS_TYPE<IPP::TransportFloatingPointType, IPP::PorosityTRTDescriptor::DiffusionDescriptor3D>;

#define EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR(CLASS_TYPE) \
    EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_2D(CLASS_TYPE) \
    EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_3D(CLASS_TYPE)

#define EXTERN_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR(CLASS_TYPE) \
    extern EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_2D(CLASS_TYPE) \
    extern EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_3D(CLASS_TYPE)




#define EXPLICIT_TEMPLATE_SCALAR_DIFFVELOCITYDESCRIPTOR(CLASS_TYPE) \
    template CLASS_TYPE<IPP::TransportFloatingPointType, IPP::DiffusionVelocityDescriptor::DiffusionDescriptor2D>; \
    template CLASS_TYPE<IPP::TransportFloatingPointType, IPP::DiffusionVelocityDescriptor::DiffusionDescriptor3D>; \

#else

#define EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_2D(CLASS_TYPE)
#define EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR_3D(CLASS_TYPE)
#define EXPLICIT_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR(CLASS_TYPE)
#define EXTERN_TEMPLATE_SCALAR_DIFFPOROSITYDESCRIPTOR(CLASS_TYPE)


#define EXPLICIT_TEMPLATE_SCALAR_DIFFVELOCITYDESCRIPTOR(CLASS_TYPE)
#endif


#endif // EXTERNTEMPLATEDESCRIPTOR_H
