# Try to find the PhreeqcRM librairies
#  PHREEQCRM_FOUND - system has PHREEQCRM lib
#  PHREEQCRM_INCLUDE_DIR - the PHREEQCRM include directory
#  PHREEQCRM_LIBRARIES - Libraries needed to use PHREEQCRM

IF (PHREEQCRM_INCLUDE_DIR AND PHREEQCRM_LIBRARIES)
  set(PHREEQCRM_FIND_QUIETLY TRUE)
ENDIF (PHREEQCRM_INCLUDE_DIR AND PHREEQCRM_LIBRARIES)

FIND_PATH(PHREEQCRM_INCLUDE_DIR NAMES PhreeqcRM.h IPhreeqc.hpp
          HINTS ${PHREEQCRM_ROOT_DIR}/include
          PATH_SUFFIXES phreeqcrm)
FIND_LIBRARY(PHREEQCRM_LIBRARIES NAMES PhreeqcRM PhreeqcRMd
             HINTS ${PHREEQCRM_ROOT_DIR}/lib/  ${PHREEQCRM_ROOT_DIR}/lib64/
              )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PhreeqcRM DEFAULT_MSG PHREEQCRM_INCLUDE_DIR PHREEQCRM_LIBRARIES)
MARK_AS_ADVANCED( PHREEQCRM_INCLUDE_DIR PHREEQCRM_LIBRARIES )
